# Cloud Build configuration for CAAS Frontend
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'NEXT_PUBLIC_API_URL=https://caas-backend-102964896009.europe-west2.run.app',
      '-t', 'gcr.io/$PROJECT_ID/caas-frontend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/caas-frontend:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/caas-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/caas-frontend:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'caas-frontend',
      '--image', 'gcr.io/$PROJECT_ID/caas-frontend:$COMMIT_SHA',
      '--region', 'europe-west2',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '512Mi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--port', '3000',
      '--set-env-vars', 'NEXT_PUBLIC_API_URL=https://caas-backend-[hash]-ew.a.run.app'
    ]

# Store images in Google Container Registry
images:
  - gcr.io/$PROJECT_ID/caas-frontend:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/caas-frontend:latest

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1200s'